import type { ElroyTriviaQuestion } from '@/lib/cannabis-trivia';
import {
  CANNABIS_TRIVIA_EXTRA,
  FREAKY_TRIVIA_EXTRA,
  MUSIC_90S_TRIVIA_EXTRA,
} from '@/lib/trivia-bank-extra';

export const CANNABIS_TRIVIA_BANK: ElroyTriviaQuestion[] = [
  {
    id: 'mechoulam-thc-year',
    category: 'cannabis',
    question: 'Israeli chemist Raphael Mechoulam first isolated THC in what year?',
    answers: ['1964', 'nineteen sixty four'],
    displayAnswer: '1964',
  },
  {
    id: 'prop-215-state',
    category: 'cannabis',
    question: 'Which US state passed Prop 215 in 1996, becoming the first to legalize medical cannabis by ballot?',
    answers: ['california', 'ca'],
    displayAnswer: 'California',
  },
  {
    id: 'uruguay-legal-year',
    category: 'cannabis',
    question: 'Uruguay became the first country to legalize recreational cannabis nationwide in what year?',
    answers: ['2013', 'twenty thirteen'],
    displayAnswer: '2013',
  },
  {
    id: 'oshaughnessy-country',
    category: 'cannabis',
    question: 'Dr. William O\'Shaughnessy introduced cannabis to Western medicine after observing it in which country?',
    answers: ['india', 'british india'],
    displayAnswer: 'India',
  },
  {
    id: 'thca-precursor',
    category: 'cannabis',
    question: 'Before decarboxylation, THC exists in raw flower primarily as what four-letter acid?',
    answers: ['thca', 't h c a', 'tetrahydrocannabinolic acid'],
    displayAnswer: 'THCA',
  },
  {
    id: 'schedule-one',
    category: 'cannabis',
    question: 'Under the US Controlled Substances Act, marijuana remains on which schedule?',
    answers: ['schedule i', 'schedule 1', 'schedule one'],
    displayAnswer: 'Schedule I',
  },
  {
    id: 'myrcene-mango',
    category: 'cannabis',
    question: 'Which terpene — abundant in mangoes — is most linked to sedating "couch-lock" profiles?',
    answers: ['myrcene', 'beta myrcene'],
    displayAnswer: 'Myrcene',
  },
  {
    id: 'blue-dream-cross',
    category: 'cannabis',
    question: 'Classic strain Blue Dream crosses Blueberry with which legendary sativa lineage?',
    answers: ['haze', 'super silver haze', 'silver haze'],
    displayAnswer: 'Haze (Super Silver Haze)',
  },
  {
    id: 'cbd-adams',
    category: 'cannabis',
    question: 'Who first isolated CBD from cannabis in 1940? (last name is enough)',
    answers: ['adams', 'roger adams'],
    displayAnswer: 'Roger Adams',
  },
  {
    id: 'cbda-precursor',
    category: 'cannabis',
    question: 'Raw hemp flower holds CBD mostly as which acid precursor before decarb?',
    answers: ['cbda', 'c b d a', 'cannabidiolic acid'],
    displayAnswer: 'CBDA',
  },
  {
    id: 'farm-bill-thc-limit',
    category: 'cannabis',
    question: 'The 2018 US Farm Bill legalized hemp with delta-9 THC below what percentage by dry weight?',
    answers: ['0.3', '0.3%', 'point 3', 'point three', 'three tenths'],
    displayAnswer: '0.3%',
  },
  {
    id: 'cannabis-cup-city',
    category: 'cannabis',
    question: 'The original High Times Cannabis Cup was famously held annually in which Dutch city?',
    answers: ['amsterdam'],
    displayAnswer: 'Amsterdam',
  },
  {
    id: 'lebanon-hash-region',
    category: 'cannabis',
    question: 'Traditional Lebanese hash production is most associated with which valley region?',
    answers: ['bekaa', 'bekaa valley', 'beqaa', 'beqaa valley'],
    displayAnswer: 'Bekaa Valley',
  },
  {
    id: 'cbn-from-thc',
    category: 'cannabis',
    question: 'When THC oxidizes with age, it degrades into which sedating minor cannabinoid discovered before CBD isolation?',
    answers: ['cbn', 'c b n', 'cannabinol'],
    displayAnswer: 'CBN (cannabinol)',
  },
  {
    id: 'charas-region',
    category: 'cannabis',
    question: 'Hand-rubbed charas hash tradition is most associated with which mountain range in South Asia?',
    answers: ['himalayas', 'himalaya', 'the himalayas'],
    displayAnswer: 'The Himalayas',
  },
  {
    id: 'hindu-kush-landrace',
    category: 'cannabis',
    question: 'The landrace genetics behind "Kush" strains trace to mountains between Afghanistan and which country?',
    answers: ['pakistan'],
    displayAnswer: 'Pakistan (Hindu Kush range)',
  },
  {
    id: 'dronabinol-brand',
    category: 'cannabis',
    question: 'Synthetic THC prescribed as Marinol is also known generically as what?',
    answers: ['dronabinol'],
    displayAnswer: 'Dronabinol (Marinol)',
  },
  {
    id: 'cole-memo-year',
    category: 'cannabis',
    question: 'The Obama-era Cole Memo guiding federal cannabis enforcement was issued in what year?',
    answers: ['2013', 'twenty thirteen'],
    displayAnswer: '2013',
  },
  {
    id: 'limonene-citrus',
    category: 'cannabis',
    question: 'Which citrus-scented terpene shares its name with a class of fruit peel oils?',
    answers: ['limonene', 'd limonene'],
    displayAnswer: 'Limonene',
  },
  {
    id: 'pinene-needle',
    category: 'cannabis',
    question: 'Which monoterpene gives pine forests their sharp aroma and often dominates "fresh" sativa-leaning cultivar profiles?',
    answers: ['pinene', 'alpha pinene', 'beta pinene', 'a pinene', 'b pinene'],
    displayAnswer: 'Pinene',
  },
  {
    id: 'nabilone-name',
    category: 'cannabis',
    question: 'The synthetic cannabinoid Cesamet is generically known as what?',
    answers: ['nabilone'],
    displayAnswer: 'Nabilone (Cesamet)',
  },
  {
    id: 'sativain-indica-naming',
    category: 'cannabis',
    question: 'Jean-Baptiste Lamarck coined the species name Cannabis indica after specimens from which country?',
    answers: ['india'],
    displayAnswer: 'India',
  },
  {
    id: 'hashish-club-paris',
    category: 'cannabis',
    question: 'The 1840s Parisian Club des Hashischins counted Charles Baudelaire and which French poet among its members?',
    answers: ['theophile gautier', 'gautier', 'theophile'],
    displayAnswer: 'Théophile Gautier',
  },
  {
    id: 'hemp-for-victory',
    category: 'cannabis',
    question: 'The US "Hemp for Victory" wartime film encouraging fiber production was released during which war?',
    answers: ['world war ii', 'world war 2', 'wwii', 'ww2', 'second world war'],
    displayAnswer: 'World War II',
  },
  {
    id: 'caryophyllene-pepper',
    category: 'cannabis',
    question: 'Beta-caryophyllene is distinctive among terpenes because it also binds what class of receptor?',
    answers: ['cb2', 'cb2 receptor', 'cannabinoid receptor 2'],
    displayAnswer: 'CB2 receptor',
  },
  {
    id: 'gw-pharma-epidiolex',
    category: 'cannabis',
    question: 'GW Pharmaceuticals\' CBD drug approved for severe epilepsy is branded what?',
    answers: ['epidiolex'],
    displayAnswer: 'Epidiolex',
  },
  {
    id: 'marihuana-tax-act',
    category: 'cannabis',
    question: 'Federal prohibition via the Marihuana Tax Act began in what year?',
    answers: ['1937', 'nineteen thirty seven'],
    displayAnswer: '1937',
  },
  {
    id: 'kief-screen',
    category: 'cannabis',
    question: 'Dry-sift hash collects trichome heads using screens measured in what unit of mesh size?',
    answers: ['microns', 'micron', 'μm'],
    displayAnswer: 'Microns',
  },
  {
    id: 'laws-hippies',
    category: 'cannabis',
    question: 'Dennis Hopper and Peter Fonda\'s 1969 road film that helped cement counterculture cannabis lore is called "Easy" what?',
    answers: ['rider', 'easy rider'],
    displayAnswer: 'Easy Rider',
  },
  {
    id: 'delta8-thc',
    category: 'cannabis',
    question: 'Delta-8-THC is an isomer of delta-9-THC differing by the location of a double bond on which carbon chain position?',
    answers: ['8th carbon', 'carbon 8', 'eighth carbon', '8'],
    displayAnswer: '8th carbon (delta-8 position)',
  },
  ...CANNABIS_TRIVIA_EXTRA,
];

export const FREAKY_TRIVIA_BANK: ElroyTriviaQuestion[] = [
  {
    id: 'story-of-o-author',
    category: 'freaky',
    question: 'The erotic novel "The Story of O" was published under the pseudonym Pauline what?',
    answers: ['reage', 'réage', 'pauline reage', 'pauline réage'],
    displayAnswer: 'Pauline Réage',
  },
  {
    id: 'kinsey-institute',
    category: 'freaky',
    question: 'Which Bloomington, Indiana research institute published the famous 1948 and 1953 sexual behavior reports?',
    answers: ['kinsey institute', 'the kinsey institute'],
    displayAnswer: 'The Kinsey Institute',
  },
  {
    id: 'sadism-namesake',
    category: 'freaky',
    question: 'The term "sadism" comes from the Marquis de who?',
    answers: ['sade', 'de sade', 'marquis de sade', 'donatien'],
    displayAnswer: 'Marquis de Sade',
  },
  {
    id: 'masochism-namesake',
    category: 'freaky',
    question: 'Masochism is named after Austrian writer Leopold von who?',
    answers: ['sacher masoch', 'sacher-masoch', 'sachermasoch'],
    displayAnswer: 'Leopold von Sacher-Masoch',
  },
  {
    id: 'grafenberg-spot',
    category: 'freaky',
    question: 'The G-spot is named after German physician Ernst what?',
    answers: ['grafenberg', 'gräfenberg'],
    displayAnswer: 'Gräfenberg',
  },
  {
    id: 'hirschfeld-institute',
    category: 'freaky',
    question: 'Magnus Hirschfeld\'s Berlin Institut für Sexualwissenschaft (destroyed in 1933) is known in English as the Institute for what field?',
    answers: ['sexual science', 'sexology'],
    displayAnswer: 'Sexual Science (Institut für Sexualwissenschaft)',
  },
  {
    id: 'stonewall-year',
    category: 'freaky',
    question: 'The Stonewall riots — a turning point for queer liberation — erupted in what year?',
    answers: ['1969', 'nineteen sixty nine'],
    displayAnswer: '1969',
  },
  {
    id: 'masters-johnson-city',
    category: 'freaky',
    question: 'Masters and Johnson conducted their pioneering sex research in which US city?',
    answers: ['st louis', 'saint louis', 'st. louis'],
    displayAnswer: 'St. Louis',
  },
  {
    id: 'havelock-ellis-book',
    category: 'freaky',
    question: 'Victorian-era scholar Havelock Ellis published a six-volume 1897–1910 work whose title ends with "Psychology of" what?',
    answers: ['studies in the psychology of sex', 'the psychology of sex'],
    displayAnswer: 'Sex (Studies in the Psychology of Sex)',
  },
  {
    id: 'tom-of-finland-name',
    category: 'freaky',
    question: 'Iconic homoerotic artist Tom of Finland\'s real last name was what?',
    answers: ['laaksonen', 'touko laaksonen'],
    displayAnswer: 'Laaksonen',
  },
  {
    id: 'hanky-code-origin',
    category: 'freaky',
    question: 'The hanky code for signaling kink interests in gay leather culture emerged in 1970s-era what US city?',
    answers: ['san francisco', 'sf'],
    displayAnswer: 'San Francisco',
  },
  {
    id: 'baker-street-condoms',
    category: 'freaky',
    question: 'Activist Jack Wrangler and performer Chi Chi LaRue built early gay adult retail around which LA neighborhood?',
    answers: ['west hollywood', 'weho'],
    displayAnswer: 'West Hollywood',
  },
  {
    id: 'hite-report-author',
    category: 'freaky',
    question: 'The 1976 bestseller documenting thousands of anonymous surveys on female orgasm was written by Shere who?',
    answers: ['hite', 'shere hite'],
    displayAnswer: 'Shere Hite',
  },
  {
    id: 'leather-bar-chicago',
    category: 'freaky',
    question: 'Chicago\'s legendary 1970s–80s leather bar on Clark Street shared its name with a ritzy neighborhood — what was the bar called?',
    answers: ['gold coast bar', 'the gold coast'],
    displayAnswer: 'Gold Coast (bar)',
  },
  {
    id: 'sodomy-law-lawrence',
    category: 'freaky',
    question: 'The 2003 Supreme Court case striking down sodomy laws was Lawrence v. what state?',
    answers: ['texas'],
    displayAnswer: 'Texas (Lawrence v. Texas)',
  },
  {
    id: 'vatsyayana-text',
    category: 'freaky',
    question: 'The ancient Sanskrit manual of love often called the Kama Sutra is attributed to Vatsyayana from which subcontinent?',
    answers: ['india', 'indian subcontinent'],
    displayAnswer: 'India',
  },
  {
    id: 'foucault-biopolitics',
    category: 'freaky',
    question: 'Michel Foucault\'s history of sexuality begins with the Victorian-era figure the "repressive" what?',
    answers: ['hypothesis', 'repressive hypothesis'],
    displayAnswer: 'Repressive hypothesis',
  },
  {
    id: 'wanda-von-sacher',
    category: 'freaky',
    question: '"Venus in Furs" (1870) was written by Austrian novelist Leopold von who?',
    answers: ['masoch', 'sacher masoch', 'sacher-masoch'],
    displayAnswer: 'Sacher-Masoch',
  },
  {
    id: 'comstock-act',
    category: 'freaky',
    question: 'Anthony Comstock\'s 1873 law criminalized mailing "obscene" materials — it is called the Comstock what?',
    answers: ['act', 'comstock act'],
    displayAnswer: 'Comstock Act',
  },
  {
    id: 'lesbian-bar-stone-wall',
    category: 'freaky',
    question: 'Before Stonewall, one of the longest-running US lesbian bars was the Mona\'s Club in which city?',
    answers: ['san francisco', 'sf'],
    displayAnswer: 'San Francisco (Mona\'s)',
  },
  ...FREAKY_TRIVIA_EXTRA,
];

export const MUSIC_90S_TRIVIA_BANK: ElroyTriviaQuestion[] = [
  {
    id: 'music90s-mariah-fantasy-sample',
    category: 'music90s',
    question: 'Mariah Carey\'s 1995 "Fantasy" famously samples which Tom Tom Club song?',
    answers: ['genius of love', 'the genius of love'],
    displayAnswer: 'Genius of Love',
  },
  {
    id: 'music90s-hiphop-bonus-illmatic',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Nas\'s "Illmatic" is deeply tied to which Queens housing project?',
    answers: ['queensbridge', 'queensbridge projects'],
    displayAnswer: 'Queensbridge',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-ready-to-die-label',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): The Notorious B.I.G.\'s "Ready to Die" came out on which Puff-founded label?',
    answers: ['bad boy', 'bad boy records', 'bad boy entertainment'],
    displayAnswer: 'Bad Boy Records',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-outkast-debut',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): OutKast\'s 1994 debut was released on which Atlanta label co-founded by L.A. Reid?',
    answers: ['laface', 'la face', 'laface records'],
    displayAnswer: 'LaFace Records',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-mos-def-talib',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Mos Def and Talib Kweli\'s "Black Star" album was named after a shop in which borough?',
    answers: ['brooklyn'],
    displayAnswer: 'Brooklyn',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-pharcyde-second',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): The Pharcyde\'s "They Want EFX" title references which East Coast duo?',
    answers: ['das efx', 'd a s e f x'],
    displayAnswer: 'Das EFX',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-scarface-geto',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Scarface fronted which Houston group on "Mind Playing Tricks on Me"?',
    answers: ['geto boys', 'the geto boys'],
    displayAnswer: 'Geto Boys',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-tupac-shakur-name',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): 2Pac was renamed after Túpac Amaru II, a revolutionary from which country?',
    answers: ['peru', 'peruvian'],
    displayAnswer: 'Peru',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-wu-producer',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): RZA\'s birth name is Robert what?',
    answers: ['diggs', 'robert diggs', 'robert fitzgerald diggs'],
    displayAnswer: 'Robert Diggs',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-de-la-sample',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): De La Soul\'s "Potholes in My Lawn" samples which P-Funk bandleader?',
    answers: ['george clinton', 'clinton'],
    displayAnswer: 'George Clinton',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-snoop-debut',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Snoop Dogg\'s 1993 debut album on Death Row was titled what?',
    answers: ['doggystyle', 'doggy style'],
    displayAnswer: 'Doggystyle',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-a-tribe-low-end',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): "The Low End Theory" features legendary jazz bassist Ron who?',
    answers: ['carter', 'ron carter'],
    displayAnswer: 'Ron Carter',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-mobb-deep-prodigy',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Mobb Deep\'s "Shook Ones Pt. II" duo is Havoc and which rapper?',
    answers: ['prodigy', 'alberto prodigy'],
    displayAnswer: 'Prodigy',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-wu-ghostface',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Ghostface Killah\'s debut solo album "Ironman" dropped in what year?',
    answers: ['1996', 'nineteen ninety six'],
    displayAnswer: '1996',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-jay-z-reasonable',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Jay-Z\'s 1996 debut "Reasonable Doubt" was released on his own label — what was it called?',
    answers: ['roc a fella', 'roc-a-fella', 'rocafella', 'roc a fella records'],
    displayAnswer: 'Roc-A-Fella Records',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-lauryn-fugees',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Before her solo album, Lauryn Hill was in which trio with Wyclef and Pras?',
    answers: ['fugees', 'the fugees'],
    displayAnswer: 'The Fugees',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-tribe-tip',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): A Tribe Called Quest\'s DJ and co-founder goes by the stage name Ali what?',
    answers: ['shaheed muhammad', 'ali shaheed muhammad'],
    displayAnswer: 'Ali Shaheed Muhammad',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-nas-producer',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Large Professor produced much of "Illmatic" — his group was Main what?',
    answers: ['source', 'main source'],
    displayAnswer: 'Main Source',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-redman-epmd',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Redman and Method Man\'s Def Squad roots trace to EPMD\'s hometown in which state?',
    answers: ['new jersey', 'nj'],
    displayAnswer: 'New Jersey',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-pac-shakur-album',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): 2Pac\'s double album released months after his death was titled "The Don Killuminati: The 7 Day" what?',
    answers: ['theory', 'the 7 day theory', '7 day theory'],
    displayAnswer: 'The 7 Day Theory',
    points: 2,
  },
  {
    id: 'music90s-rnb-babyface-label',
    category: 'music90s',
    question: 'Producer Babyface co-founded which Atlanta R&B label behind TLC and Toni Braxton?',
    answers: ['laface', 'la face', 'laface records'],
    displayAnswer: 'LaFace Records',
  },
  {
    id: 'music90s-rnb-whitney-bodyguard',
    category: 'music90s',
    question: 'Whitney Houston\'s "I Will Always Love You" dominated 1992 after which film soundtrack?',
    answers: ['the bodyguard', 'bodyguard'],
    displayAnswer: 'The Bodyguard',
  },
  {
    id: 'music90s-rock-nirvana-producer',
    category: 'music90s',
    question: 'Nirvana\'s "Nevermind" was produced by Butch what?',
    answers: ['vig', 'butch vig'],
    displayAnswer: 'Butch Vig',
  },
  {
    id: 'music90s-rock-pearl-jam-debut',
    category: 'music90s',
    question: 'Pearl Jam\'s 1991 debut album shares its name with which basketball player?',
    answers: ['mookie blaylock', 'blaylock'],
    displayAnswer: 'Mookie Blaylock (Ten)',
  },
  {
    id: 'music90s-hiphop-bonus-gangstarr-dj',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Gang Starr\'s DJ Premier partnered with rapper Guru — Guru\'s birth name was Keith what?',
    answers: ['elam', 'keith elam'],
    displayAnswer: 'Keith Elam',
    points: 2,
  },
  ...MUSIC_90S_TRIVIA_EXTRA,
];

export const ELROY_TRIVIA_BANK: ElroyTriviaQuestion[] = [
  ...CANNABIS_TRIVIA_BANK,
  ...FREAKY_TRIVIA_BANK,
  ...MUSIC_90S_TRIVIA_BANK,
];
