import type { ElroyTriviaQuestion } from '@/lib/cannabis-trivia';

export const CANNABIS_TRIVIA_EXTRA: ElroyTriviaQuestion[] = [
  {
    id: 'cannabis-norml-founder',
    category: 'cannabis',
    question: 'The US reform group NORML was founded in 1970 by attorney Keith who?',
    answers: ['stroup', 'keith stroup'],
    displayAnswer: 'Keith Stroup',
  },
  {
    id: 'cannabis-jack-herer-book',
    category: 'cannabis',
    question: 'Activist Jack Herer\'s influential hemp history book is titled "The Emperor Wears No" what?',
    answers: ['clothes', 'no clothes'],
    displayAnswer: 'Clothes (The Emperor Wears No Clothes)',
  },
  {
    id: 'cannabis-amendment-64-state',
    category: 'cannabis',
    question: 'Which US state passed Amendment 64 in 2012, legalizing adult-use sales starting in 2014?',
    answers: ['colorado', 'co'],
    displayAnswer: 'Colorado',
  },
  {
    id: 'cannabis-i502-state',
    category: 'cannabis',
    question: 'Washington voters approved adult-use cannabis through Initiative 502 in what year?',
    answers: ['2012', 'twenty twelve'],
    displayAnswer: '2012',
  },
  {
    id: 'cannabis-measure-91-state',
    category: 'cannabis',
    question: 'Oregon\'s Measure 91 legalized recreational cannabis in what year?',
    answers: ['2014', 'twenty fourteen'],
    displayAnswer: '2014',
  },
  {
    id: 'cannabis-hash-bash-city',
    category: 'cannabis',
    question: 'The annual Hash Bash rally has been held since 1972 on the campus of the University of Michigan in which city?',
    answers: ['ann arbor', 'annarbor'],
    displayAnswer: 'Ann Arbor',
  },
  {
    id: 'cannabis-russo-entourage',
    category: 'cannabis',
    question: 'Physician Ethan Russo argued that whole-plant synergy between cannabinoids and terpenes should be called the what effect?',
    answers: ['entourage', 'entourage effect', 'the entourage effect'],
    displayAnswer: 'Entourage effect',
  },
  {
    id: 'cannabis-cbg-mother',
    category: 'cannabis',
    question: 'The non-intoxicating "stem cell" cannabinoid CBG is short for cannabigerol and is often called the what cannabinoid?',
    answers: ['mother', 'mother cannabinoid'],
    displayAnswer: 'Mother cannabinoid (CBG)',
  },
  {
    id: 'cannabis-thcv-varin',
    category: 'cannabis',
    question: 'The appetite-modulating homolog THCV is formally known as tetrahydrocannabivarin — the "V" indicates it is a what-type variant?',
    answers: ['varin', 'propyl', 'propyl side chain'],
    displayAnswer: 'Varin (propyl side chain)',
  },
  {
    id: 'cannabis-linalool-lavender',
    category: 'cannabis',
    question: 'The floral terpene linalool is also dominant in essential oil from which purple flowering plant?',
    answers: ['lavender'],
    displayAnswer: 'Lavender',
  },
  {
    id: 'cannabis-humulene-hops',
    category: 'cannabis',
    question: 'Humulene — shared by cannabis and beer — is most abundant in the brewing ingredient called what?',
    answers: ['hops', 'hop'],
    displayAnswer: 'Hops',
  },
  {
    id: 'cannabis-durban-poison-port',
    category: 'cannabis',
    question: 'The landrace sativa Durban Poison takes its name from a port city in which African country?',
    answers: ['south africa'],
    displayAnswer: 'South Africa (Durban)',
  },
  {
    id: 'cannabis-rif-mountains',
    category: 'cannabis',
    question: 'Traditional Moroccan kif cultivation is concentrated in the Rif Mountains of which country?',
    answers: ['morocco'],
    displayAnswer: 'Morocco',
  },
  {
    id: 'cannabis-ketama-region',
    category: 'cannabis',
    question: 'Blonde Moroccan export hash from the Rif is often labeled by the valley region of what?',
    answers: ['ketama', 'ketama valley'],
    displayAnswer: 'Ketama',
  },
  {
    id: 'cannabis-humboldt-county',
    category: 'cannabis',
    question: 'Legacy-era outdoor cannabis in Northern California is most associated with which county name-checked in strain lore?',
    answers: ['humboldt', 'humboldt county'],
    displayAnswer: 'Humboldt County',
  },
  {
    id: 'cannabis-mendocino-county',
    category: 'cannabis',
    question: 'The Emerald Triangle includes Humboldt, Trinity, and which other Northern California county?',
    answers: ['mendocino', 'mendocino county'],
    displayAnswer: 'Mendocino County',
  },
  {
    id: 'cannabis-live-resin-freeze',
    category: 'cannabis',
    question: 'Live resin concentrates preserve volatile terpenes by flash-freezing plant material at what stage?',
    answers: ['harvest', 'at harvest', 'immediately after harvest'],
    displayAnswer: 'At harvest (flash-frozen fresh)',
  },
  {
    id: 'cannabis-rosin-press',
    category: 'cannabis',
    question: 'Solventless rosin is collected by applying heat and mechanical what to hash or flower?',
    answers: ['pressure'],
    displayAnswer: 'Pressure (heat + pressure)',
  },
  {
    id: 'cannabis-ice-water-hash',
    category: 'cannabis',
    question: 'Bubble hash made with stirred ice water is also called ice-water or what-style hash?',
    answers: ['bubble', 'bubble hash', 'ice hash'],
    displayAnswer: 'Bubble hash (ice-water hash)',
  },
  {
    id: 'cannabis-trichome-calyx',
    category: 'cannabis',
    question: 'Most cannabinoid-rich trichomes cap the female flower structures called what?',
    answers: ['calyx', 'calyxes', 'calyces', 'bracts'],
    displayAnswer: 'Calyxes (bracts)',
  },
  {
    id: 'cannabis-samuel-calhoun',
    category: 'cannabis',
    question: 'The 1936 anti-marijuana film "Reefer Madness" was originally released under which exploitative title referencing a forbidden herb?',
    answers: ['tell your children', 'tell your children reefer madness'],
    displayAnswer: 'Tell Your Children',
  },
  {
    id: 'cannabis-canada-legal-year',
    category: 'cannabis',
    question: 'Canada legalized recreational cannabis nationwide through the Cannabis Act in what year?',
    answers: ['2018', 'twenty eighteen'],
    displayAnswer: '2018',
  },
  {
    id: 'cannabis-lesotho-license',
    category: 'cannabis',
    question: 'Which small African kingdom was among the first on the continent to grant commercial medical cannabis cultivation licenses in 2017?',
    answers: ['lesotho'],
    displayAnswer: 'Lesotho',
  },
  {
    id: 'cannabis-panama-red',
    category: 'cannabis',
    question: 'The sativa landrace "Panama Red" became famous through exports from which Central American country?',
    answers: ['panama'],
    displayAnswer: 'Panama',
  },
  {
    id: 'cannabis-colombian-gold',
    category: 'cannabis',
    question: 'The classic landrace "Colombian Gold" originated in the Santa Marta mountains of which country?',
    answers: ['colombia'],
    displayAnswer: 'Colombia',
  },
  {
    id: 'cannabis-judge-young-2018',
    category: 'cannabis',
    question: 'The 2018 Farm Bill removed hemp from Schedule I by redefining it under the Agricultural Marketing Act — it was signed by President who?',
    answers: ['trump', 'donald trump'],
    displayAnswer: 'Donald Trump',
  },
  {
    id: 'cannabis-sativex-brand',
    category: 'cannabis',
    question: 'GW Pharmaceuticals\' THC/CBD oromucosal spray approved in multiple countries is branded what?',
    answers: ['sativex'],
    displayAnswer: 'Sativex',
  },
  {
    id: 'cannabis-terpinolene',
    category: 'cannabis',
    question: 'Jack Herer and Super Silver Haze are often cited for a complex, floral-herbal terp profile dominated by which ten-carbon monoterpene?',
    answers: ['terpinolene'],
    displayAnswer: 'Terpinolene',
  },
  {
    id: 'cannabis-ocimene',
    category: 'cannabis',
    question: 'Sweet, herbaceous notes in some tropical cultivars come from a acyclic monoterpene also found in orchids and mint — name it?',
    answers: ['ocimene'],
    displayAnswer: 'Ocimene',
  },
  {
    id: 'cannabis-borneol',
    category: 'cannabis',
    question: 'Camphoraceous cooling notes in certain Asian landrace lines come from a terpenoid alcohol also used in traditional medicine — what is it?',
    answers: ['borneol', 'iso borneol', 'isoborneol'],
    displayAnswer: 'Borneol',
  },
  {
    id: 'cannabis-geraniol',
    category: 'cannabis',
    question: 'Rose-like aromas in some cultivars come from a monoterpenoid alcohol that is also a primary component of citronella oil — what is it?',
    answers: ['geraniol'],
    displayAnswer: 'Geraniol',
  },
  {
    id: 'cannabis-dagga-slang',
    category: 'cannabis',
    question: 'In South African slang, cannabis is often called "dagga" — a term derived from Khoikhoi via which colonial language?',
    answers: ['dutch', 'afrikaans'],
    displayAnswer: 'Dutch / Afrikaans (dagga)',
  },
  {
    id: 'cannabis-bhang-india',
    category: 'cannabis',
    question: 'Traditional Indian milk-based preparation bhang is most associated with the spring festival of what color?',
    answers: ['holi'],
    displayAnswer: 'Holi',
  },
  {
    id: 'cannabis-nabiximols',
    category: 'cannabis',
    question: 'The standardized 1:1 THC to CBD extract used in Sativex is known generically as what?',
    answers: ['nabiximols'],
    displayAnswer: 'Nabiximols',
  },
];

export const FREAKY_TRIVIA_EXTRA: ElroyTriviaQuestion[] = [
  {
    id: 'freaky-audre-lorde-essay',
    category: 'freaky',
    question: 'Poet Audre Lorde\'s 1978 essay framing eroticism as power is titled "Uses of the" what?',
    answers: ['erotic', 'the erotic'],
    displayAnswer: 'Erotic ("Uses of the Erotic")',
  },
  {
    id: 'freaky-betty-dodson',
    category: 'freaky',
    question: 'Sex educator Betty Dodson became famous in the 1970s for teaching women self-pleasure through "Bodysex" what?',
    answers: ['workshops', 'bodysex workshops', 'classes'],
    displayAnswer: 'Workshops (Bodysex)',
  },
  {
    id: 'freaky-anais-nin-delta',
    category: 'freaky',
    question: 'Erotic diarist Anaïs Nin\'s posthumous story collection "Delta of" what was published in 1977?',
    answers: ['venus', 'delta of venus'],
    displayAnswer: 'Venus (Delta of Venus)',
  },
  {
    id: 'freaky-susie-bright',
    category: 'freaky',
    question: 'Feminist erotica editor Susie Bright founded the annual "Best American Erotica" series in what decade?',
    answers: ['1990s', 'nineties', '90s'],
    displayAnswer: '1990s',
  },
  {
    id: 'freaky-good-vibrations-city',
    category: 'freaky',
    question: 'Worker-owned retailer Good Vibrations opened its first boutique in which US city in 1977?',
    answers: ['san francisco', 'sf'],
    displayAnswer: 'San Francisco',
  },
  {
    id: 'freaky-international-mr-leather',
    category: 'freaky',
    question: 'The International Mr. Leather contest — a major leather community event — is held annually in which city?',
    answers: ['chicago'],
    displayAnswer: 'Chicago',
  },
  {
    id: 'freaky-leather-archives-city',
    category: 'freaky',
    question: 'The Leather Archives & Museum preserving kink history is located in which Midwestern US city?',
    answers: ['chicago'],
    displayAnswer: 'Chicago',
  },
  {
    id: 'freaky-mattachine-founder',
    category: 'freaky',
    question: 'Early US homophile group the Mattachine Society was co-founded in 1950 by Harry what?',
    answers: ['hay', 'harry hay'],
    displayAnswer: 'Harry Hay',
  },
  {
    id: 'freaky-sylvia-rivera-star',
    category: 'freaky',
    question: 'Activist Sylvia Rivera co-founded STAR — Street Transvestite Action what?',
    answers: ['revolutionaries', 'street transvestite action revolutionaries'],
    displayAnswer: 'Revolutionaries (STAR)',
  },
  {
    id: 'freaky-marsha-p-johnson',
    category: 'freaky',
    question: 'Stonewall veteran Marsha P. Johnson co-founded STAR with Sylvia Rivera — Marsha\'s middle initial stood for what phrase?',
    answers: ['pay it no mind'],
    displayAnswer: '"Pay it no mind"',
  },
  {
    id: 'freaky-windsor-doma',
    category: 'freaky',
    question: 'Edie Windsor\'s 2013 Supreme Court case struck down a key section of DOMA — the case was United States v. what?',
    answers: ['windsor', 'edie windsor'],
    displayAnswer: 'Windsor',
  },
  {
    id: 'freaky-obergefell-year',
    category: 'freaky',
    question: 'The Supreme Court established nationwide same-sex marriage in Obergefell v. Hodges in what year?',
    answers: ['2015', 'twenty fifteen'],
    displayAnswer: '2015',
  },
  {
    id: 'freaky-bowers-hardwick',
    category: 'freaky',
    question: 'Lawrence v. Texas (2003) overturned the 1986 sodomy precedent Bowers v. Hardwick — Hardwick was from which state?',
    answers: ['georgia'],
    displayAnswer: 'Georgia (Bowers v. Hardwick)',
  },
  {
    id: 'freaky-dr-ruth-country',
    category: 'freaky',
    question: 'Media sex therapist Dr. Ruth Westheimer was born in which country before emigrating to Palestine and later the US?',
    answers: ['germany', 'weimar germany'],
    displayAnswer: 'Germany',
  },
  {
    id: 'freaky-margaret-sanger',
    category: 'freaky',
    question: 'Birth-control pioneer Margaret Sanger founded the organization that became what modern reproductive health nonprofit?',
    answers: ['planned parenthood', 'planned parenthood federation'],
    displayAnswer: 'Planned Parenthood',
  },
  {
    id: 'freaky-henry-miller-tropic',
    category: 'freaky',
    question: 'Henry Miller\'s banned 1934 Paris novel about expatriate bohemia is "Tropic of" what?',
    answers: ['cancer', 'tropic of cancer'],
    displayAnswer: 'Cancer (Tropic of Cancer)',
  },
  {
    id: 'freaky-lady-chatterley-trial',
    category: 'freaky',
    question: 'D.H. Lawrence\'s "Lady Chatterley\'s Lover" was banned for explicit depictions of an affair between an aristocrat and her estate\'s what?',
    answers: ['gamekeeper', 'the gamekeeper', 'groundskeeper'],
    displayAnswer: 'Gamekeeper',
  },
  {
    id: 'freaky-obscene-publications-act',
    category: 'freaky',
    question: 'The UK\'s 1959 Obscene Publications Act introduced a "literary merit" defense famously used in trials over which Lawrence novel?',
    answers: ['lady chatterleys lover', 'lady chatterley', 'chatterley'],
    displayAnswer: 'Lady Chatterley\'s Lover',
  },
  {
    id: 'freaky-fetlife-launch',
    category: 'freaky',
    question: 'Kink-oriented social network FetLife launched to the public in what year?',
    answers: ['2008', 'twenty eight', 'twenty oh eight'],
    displayAnswer: '2008',
  },
  {
    id: 'freaky-san-francisco-armory',
    category: 'freaky',
    question: 'The Mission District armory building in San Francisco was famously leased by which adult production company?',
    answers: ['kink com', 'kink.com', 'kink'],
    displayAnswer: 'Kink.com',
  },
  {
    id: 'freaky-peter-acworth',
    category: 'freaky',
    question: 'Founder of the San Francisco Armory studio Kink.com — entrepreneur Peter what?',
    answers: ['acworth', 'peter acworth'],
    displayAnswer: 'Peter Acworth',
  },
  {
    id: 'freaky-beate-uhse',
    category: 'freaky',
    question: 'German pilot Beate Uhse opened one of Europe\'s first mail-order erotica businesses after WWII — her brand became a chain of what shops?',
    answers: ['sex shops', 'adult shops', 'erotica shops'],
    displayAnswer: 'Sex shops (Beate Uhse)',
  },
  {
    id: 'freaky-olympia-press',
    category: 'freaky',
    question: 'Paris publisher Olympia Press issued controversial editions of Burroughs\' "Naked Lunch" and Nabokov\'s "Lolita" from which city?',
    answers: ['paris'],
    displayAnswer: 'Paris (Olympia Press)',
  },
  {
    id: 'freaky-harvey-milk-city',
    category: 'freaky',
    question: 'Assassinated supervisor Harvey Milk was elected to office in which California city in 1977?',
    answers: ['san francisco', 'sf'],
    displayAnswer: 'San Francisco',
  },
  {
    id: 'freaky-brief-briefs',
    category: 'freaky',
    question: 'Queer theorist Eve Kosofsky Sedgwick\'s 1990 book "Epistemology of the Closet" helped establish what academic field\'s literary branch?',
    answers: ['queer theory', 'queer studies'],
    displayAnswer: 'Queer theory',
  },
  {
    id: 'freaky-judith-butler',
    category: 'freaky',
    question: 'Philosopher Judith Butler\'s 1990 book "Gender Trouble" popularized the idea of gender as what kind of performance?',
    answers: ['performative', 'a performative', 'performance'],
    displayAnswer: 'Performative (gender performance)',
  },
  {
    id: 'freaky-rubber-dublin',
    category: 'freaky',
    question: 'Annual European fetish convention "Darklands" draws thousands of leather and rubber enthusiasts to which Belgian city?',
    answers: ['antwerp'],
    displayAnswer: 'Antwerp (Darklands)',
  },
  {
    id: 'freaky-vatsyayana-kama',
    category: 'freaky',
    question: 'The Kama Sutra compiler Vatsyayana is traditionally said to have lived during which Indian empire\'s Gupta period?',
    answers: ['gupta', 'gupta empire'],
    displayAnswer: 'Gupta Empire',
  },
  {
    id: 'freaky-alan-parker-pink',
    category: 'freaky',
    question: 'The 1982 film "Pink Flamingos" that pushed obscenity boundaries was directed by John who?',
    answers: ['waters', 'john waters'],
    displayAnswer: 'John Waters',
  },
  {
    id: 'freaky-mapplethorpe-cincinnati',
    category: 'freaky',
    question: 'Photographer Robert Mapplethorpe\'s 1990 Cincinnati exhibition trial centered on whether his work was legally what?',
    answers: ['obscene', 'obscenity'],
    displayAnswer: 'Obscene (obscenity trial)',
  },
  {
    id: 'freaky-bathhouse-raid',
    category: 'freaky',
    question: 'Toronto police raided gay bathhouses in 1981 in Operation Soap — protests that followed are remembered as Canada\'s equivalent to what NY uprising?',
    answers: ['stonewall', 'stonewall riots'],
    displayAnswer: 'Stonewall',
  },
  {
    id: 'freaky-chromosome-xxy',
    category: 'freaky',
    question: 'Klinefelter syndrome in sexology literature involves an extra X chromosome — the karyotype is what?',
    answers: ['xxy', '47 xxy', '47xxy'],
    displayAnswer: 'XXY (47,XXY)',
  },
];

export const MUSIC_90S_TRIVIA_EXTRA: ElroyTriviaQuestion[] = [
  {
    id: 'music90s-hiphop-bonus-del-cube',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Del the Funky Homosapien is the cousin of which N.W.A co-founder?',
    answers: ['ice cube', 'cube'],
    displayAnswer: 'Ice Cube',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-souls-mischief',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): "93 \'til Infinity" crew Souls of Mischief hail from which Bay Area city?',
    answers: ['oakland'],
    displayAnswer: 'Oakland',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-hieroglyphics',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Del, Casual, and Pep Love were core members of Oakland collective Hieroglyphics — their logo is a stylized what?',
    answers: ['third eye', 'eye', 'all seeing eye'],
    displayAnswer: 'Third eye (Hieroglyphics logo)',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-pharcyde-labcab',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): The Pharcyde\'s 1995 "Labcabincalifornia" features beats from a Detroit producer who later became known as what?',
    answers: ['j dilla', 'jdilla', 'jay dee'],
    displayAnswer: 'J Dilla',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-troy-sample',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Pete Rock & CL Smooth\'s "They Reminisce Over You (T.R.O.Y.)" samples a horn line from which jazz-funk group\'s "Today"?',
    answers: ['tom scott', 'the tom scott quintet', 'tom scott quintet'],
    displayAnswer: 'Tom Scott Quintet',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-tribe-bonita',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): "Bonita Applebum" samples "Daylight" by which jazz-funk keyboardist?',
    answers: ['ronnie laws', 'ronnie law'],
    displayAnswer: 'Ronnie Laws',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-de-la-jaydee',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): De La Soul\'s 1996 "Stakes Is High" was produced by which Detroit beatmaker later known as J Dilla?',
    answers: ['jay dee', 'j dilla', 'jdilla', 'james yancey'],
    displayAnswer: 'Jay Dee (J Dilla)',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-slum-detroit',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Slum Village\'s founding trio included Baatin, T3, and which producer born James Yancey?',
    answers: ['jay dee', 'j dilla', 'james yancey'],
    displayAnswer: 'Jay Dee (J Dilla)',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-common-chi',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Rapper Common (then Common Sense) grew up in which Midwestern city?',
    answers: ['chicago'],
    displayAnswer: 'Chicago',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-cypress-sen',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Cypress Hill MC Sen Dog was born in which Caribbean island nation before moving to LA?',
    answers: ['cuba', 'cuban'],
    displayAnswer: 'Cuba',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-odb-name',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Wu-Tang\'s Ol\' Dirty Bastard was born Russell Tyrone what?',
    answers: ['jones', 'russell jones'],
    displayAnswer: 'Jones',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-method-man-name',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Wu-Tang\'s Method Man was born Clifford Smith in which New York borough?',
    answers: ['staten island', 'staten'],
    displayAnswer: 'Staten Island',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-raekwon-album',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Raekwon\'s 1995 solo classic "Only Built 4 Cuban Linx..." is nicknamed the what tape?',
    answers: ['purple', 'purple tape'],
    displayAnswer: 'Purple tape',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-gza-album',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): GZA\'s 1995 solo album produced largely by RZA shares its title with a medieval weapon — name the album?',
    answers: ['liquid swords', 'liquid sword'],
    displayAnswer: 'Liquid Swords',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-biggie-name',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): The Notorious B.I.G. was born Christopher George Latore what?',
    answers: ['wallace', 'christopher wallace'],
    displayAnswer: 'Wallace',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-jay-z-marcy',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Jay-Z\'s Marcy Projects nickname "Jazzy" later became his stage name — the projects are in which Brooklyn neighborhood?',
    answers: ['bedford stuyvesant', 'bed stuy', 'bedstuy'],
    displayAnswer: 'Bedford-Stuyvesant (Marcy)',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-nas-live-bbq',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Nas\'s first notable appearance was on Main Source\'s "Live at the BBQ" in what year?',
    answers: ['1991', 'nineteen ninety one'],
    displayAnswer: '1991',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-mf-doom-kmd',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): MF DOOM first rapped as Zev Love X in which early 90s group with his brother DJ Subroc?',
    answers: ['kmd', 'k m d'],
    displayAnswer: 'KMD',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-warren-g-sample',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Warren G and Nate Dogg\'s "Regulate" samples Michael McDonald\'s "I Keep Forgettin\'" — Warren is stepbrother to which producer?',
    answers: ['dr dre', 'dre', 'andre young'],
    displayAnswer: 'Dr. Dre',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-nate-dogg-name',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Singer Nate Dogg was born Nathaniel Dwayne what?',
    answers: ['hale', 'nathaniel hale'],
    displayAnswer: 'Hale',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-pac-me-against',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): 2Pac\'s 1995 album that debuted at #1 while he was incarcerated is called "Me Against the" what?',
    answers: ['world', 'me against the world'],
    displayAnswer: 'World (Me Against the World)',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-eazy-death',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): N.W.A co-founder Eazy-E died in 1995 from complications of what illness?',
    answers: ['aids', 'hiv aids', 'hiv'],
    displayAnswer: 'AIDS',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-ice-cube-solo',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Ice Cube\'s first solo album after leaving N.W.A was "AmeriKKKa\'s Most" what?',
    answers: ['wanted', 'most wanted'],
    displayAnswer: 'Wanted (AmeriKKKa\'s Most Wanted)',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-public-enemy-fear',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Public Enemy\'s 1990 album "Fear of a Black Planet" features "Fight the Power" on the soundtrack of which Spike Lee film?',
    answers: ['do the right thing'],
    displayAnswer: 'Do the Right Thing',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-bdp-edutainment',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Boogie Down Productions\' 1990 album "Edutainment" was the last with DJ Scott La Rock\'s partner — MC name?',
    answers: ['krs one', 'krs-one', 'krsone', 'lawrence krissna parker'],
    displayAnswer: 'KRS-One',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-rakim-paid',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Eric B & Rakim\'s "Paid in Full" (1987) was sampled heavily in the 90s — Rakim\'s birth name is William Michael Griffin what?',
    answers: ['jr', 'junior', 'william michael griffin jr'],
    displayAnswer: 'Griffin Jr.',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-wu-forever',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Wu-Tang\'s 1997 double album sequel to "36 Chambers" is titled "Wu-Tang" what?',
    answers: ['forever', 'wu tang forever'],
    displayAnswer: 'Forever (Wu-Tang Forever)',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-big-life-after',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): The Notorious B.I.G.\'s posthumous 1997 double album is "Life After" what?',
    answers: ['death', 'life after death'],
    displayAnswer: 'Death (Life After Death)',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-mobb-havoc',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Mobb Deep producer Havoc was born Kejuan Muchita in which borough?',
    answers: ['queens', 'queensbridge'],
    displayAnswer: 'Queens',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-onyx-bacdafucup',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): Onyx\'s 1993 debut "Bacdafucup" was released on which Def Jam affiliate label run by Rush?',
    answers: ['rush associated labels', 'ral', 'rush'],
    displayAnswer: 'RAL (Rush Associated Labels)',
    points: 2,
  },
  {
    id: 'music90s-hiphop-bonus-lords-furious',
    category: 'music90s',
    question: '🎤 BONUS (2 pts): The Fugees\' 1996 breakout "The Score" includes a cover of "Killing Me Softly" originally by Lori who?',
    answers: ['lieberman', 'lori lieberman'],
    displayAnswer: 'Lori Lieberman (via Roberta Flack hit)',
    points: 2,
  },
  {
    id: 'music90s-rnb-tlc-waterfalls',
    category: 'music90s',
    question: 'TLC\'s 1995 hit "Waterfalls" warns about chasing illusions — it appears on which album also featuring "Creep"?',
    answers: ['crazysexycool', 'crazy sexy cool'],
    displayAnswer: 'CrazySexyCool',
  },
  {
    id: 'music90s-rnb-boyz-ii-men',
    category: 'music90s',
    question: 'Boyz II Men\'s "End of the Road" spent a record 13 weeks at #1 in 1992 — it appeared on the soundtrack for which Eddie Murphy film?',
    answers: ['boomerang'],
    displayAnswer: 'Boomerang',
  },
  {
    id: 'music90s-rock-radiohead-ok',
    category: 'music90s',
    question: 'Radiohead\'s 1997 album "OK Computer" opens with "Airbag" and closes with "The Tourist" — it was recorded largely in which country?',
    answers: ['england', 'united kingdom', 'uk', 'britain'],
    displayAnswer: 'England (UK)',
  },
];
